variable rg_name { default = "devops-agent-rg" }
variable vnet_rg_name { default = "devops-rg" }
variable vnet_name { default = "devopsvnet" }
variable vnet_subnet_name { default = "devopssubnet" }
variable vnet_nsg_name { default = "devopsnsg" }
variable diag_store_name { default = "integrationdc6rgdiag1" }
variable diag_store_rg { default = "RMS-Integration-RG" }
variable vm_name { default = "devopsvm" }
variable vm_name_win { default = "devopswindowvm" }
variable cloud_init_file { default = "cloud-init.txt" }
variable windows_init_file { default = "devops_win.ps1" }
variable devops_url { default = "https://dev.azure.com/<DEVOPS ORGANIZATION>" }
variable devops_pat { default = "rdbgw5a3s...." }
variable devops_win_pat { default = "rdbgw5a3s...." }
variable admin_password { default = "Passw0rd1!" }
variable devops_pool { default = "DevOps Agent Self-Hosted Pool" }
variable devops_agent_name { default = "SelfHostedAgent01" }
variable devops_win_agent_name { default = "WindowsSelfHostedAgent01" }
variable ssh_pub_key { default = "ssh-rsa AAAAB3NzaC1yc2...."}
